-- Клубок: схема базы событий (Supabase / Postgres)
-- Выполнить в Supabase → SQL Editor → Run. Скрипт идемпотентный, можно запускать повторно.
-- Площадка вынесена в отдельную сущность place, events ссылается на неё через events.place.

create table if not exists public.place (
  id      bigint generated by default as identity primary key,
  name    varchar not null,
  address varchar,
  phone   varchar,
  link    varchar,
  lat     double precision,
  lng     double precision
);

-- Имя площадки — ключ сопоставления при сборе, поэтому оно уникально.
create unique index if not exists place_name_idx on public.place (lower(name));

-- Координаты для карты «Площадки» на сайте. create table if not exists не трогает
-- существующую таблицу, поэтому добавляем отдельно.
alter table public.place add column if not exists lat double precision;
alter table public.place add column if not exists lng double precision;

create table if not exists public.events (
  id          text primary key,               -- sha1-хэш из коллектора
  title       text not null,
  short       text,
  "desc"      text,
  date        date,                            -- разовое событие
  wd          smallint[],                      -- регулярное: дни недели 0=пн
  time        text not null default '10:00',
  dur         text,
  place       bigint references public.place (id) on delete set null,
  age_min     smallint not null default 3,
  age_max     smallint not null default 10,
  age_label   text,
  price       text,
  image       text,
  category       text,                         -- см. collector/lib/category.mjs
  category_label text,
  source      jsonb not null default '{}',     -- {id,name,kind,url,cta}
  source_url  text generated always as (source->>'url') stored,
  hash        text,                            -- ключ дедупликации между источниками
  status      text not null default 'approved' -- pending | approved | hidden
                check (status in ('pending','approved','hidden')),
  fetched_at  timestamptz default now(),
  updated_at  timestamptz default now()
);

-- create table if not exists не трогает уже существующую таблицу,
-- поэтому новые колонки добавляем отдельно.
alter table public.events add column if not exists category       text;
alter table public.events add column if not exists category_label text;

create index if not exists events_date_idx   on public.events (date);
create index if not exists events_status_idx on public.events (status);
create index if not exists events_place_idx  on public.events (place);
create unique index if not exists events_hash_idx on public.events (hash) where hash is not null;

-- Сайту отдаём только одобренное и уже с раскрытой площадкой,
-- в той форме, которую фронтенд читает без преобразований.
-- create or replace не умеет менять типы колонок представления, поэтому пересоздаём.
drop view if exists public.events_public;

create view public.events_public as
select e.id, e.title, e.short, e."desc",
       to_char(e.date, 'YYYY-MM-DD') as date,
       e.wd, e.time, e.dur,
       p.name    as place,
       p.address as address,
       p.phone   as "placePhone",
       p.link    as "placeLink",
       p.lat     as lat,
       p.lng     as lng,
       array[e.age_min, e.age_max] as age,
       e.age_label as "ageLabel",
       e.price, e.image, e.category, e.category_label as "categoryLabel", e.source
from public.events e
left join public.place p on p.id = e.place
where e.status = 'approved'
  -- нижняя граница — начало текущей недели: UI позволяет уйти назад по стрелке «‹»
  and (e.date is null or e.date >= date_trunc('week', current_date)::date)
order by e.date nulls last, e.time;

-- Площадка по имени: находим существующую или создаём. Адрес и координаты дополняем,
-- но не затираем вручную выправленные (coalesce от текущего значения).
-- Раньше функция была на два аргумента — сносим старую сигнатуру перед пересозданием.
drop function if exists public.resolve_place(text, text);
create or replace function public.resolve_place(
  p_name    text,
  p_address text,
  p_lat     double precision default null,
  p_lng     double precision default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare v_id bigint;
begin
  if p_name is null or btrim(p_name) = '' then return null; end if;

  select id into v_id from public.place where lower(name) = lower(btrim(p_name));
  if v_id is null then
    insert into public.place (name, address, lat, lng)
    values (btrim(p_name), p_address, p_lat, p_lng)
    returning id into v_id;
  elsif p_address is not null or p_lat is not null or p_lng is not null then
    update public.place set
      address = coalesce(address, p_address),
      lat     = coalesce(lat, p_lat),
      lng     = coalesce(lng, p_lng)
    where id = v_id;
  end if;
  return v_id;
end;
$$;

-- Upsert из коллектора: обновляет содержимое, но НЕ трогает status,
-- поэтому ручное одобрение/скрытие переживает ночные прогоны.
create or replace function public.upsert_events(payload jsonb)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare n integer;
begin
  create temp table _incoming on commit drop as
  select p.id, p.title, p.short, p."desc", p.date, p.wd, p.time, p.dur,
         public.resolve_place(p.place_name, p.place_address, p.place_lat, p.place_lng) as place,
         p.age_min, p.age_max, p.age_label, p.price, p.image, p.category, p.category_label, p.source,
         p.hash, p.status, p.fetched_at
  from jsonb_to_recordset(payload) as p(
    id text, title text, short text, "desc" text, date date, wd smallint[],
    time text, dur text, place_name text, place_address text,
    place_lat double precision, place_lng double precision,
    age_min smallint, age_max smallint, age_label text, price text, image text,
    category text, category_label text,
    source jsonb, hash text, status text, fetched_at timestamptz
  );

  -- Тот же hash, но другой id = дубль из второго источника: старую запись убираем.
  -- Скрытые вручную не удаляем, а исключаем из вставки — иначе они вернутся на сайт.
  delete from public.events d
  using _incoming p
  where d.hash = p.hash and d.id <> p.id and d.status <> 'hidden';

  delete from _incoming p
  where p.hash is not null
    and exists (select 1 from public.events h where h.hash = p.hash and h.status = 'hidden');

  insert into public.events as e
    (id, title, short, "desc", date, wd, time, dur, place,
     age_min, age_max, age_label, price, image, category, category_label, source, hash, status, fetched_at, updated_at)
  select id, title, short, "desc", date, wd, time, dur, place,
         age_min, age_max, age_label, price, image, category, category_label, source, hash, status, fetched_at, now()
  from _incoming
  on conflict (id) do update set
    title          = excluded.title,
    short          = excluded.short,
    "desc"         = excluded."desc",
    date           = excluded.date,
    wd             = excluded.wd,
    time           = excluded.time,
    dur            = excluded.dur,
    place          = coalesce(excluded.place, e.place),
    age_min        = excluded.age_min,
    age_max        = excluded.age_max,
    age_label      = excluded.age_label,
    price          = excluded.price,
    image          = coalesce(excluded.image, e.image),
    category       = excluded.category,
    category_label = excluded.category_label,
    source         = excluded.source,
    hash           = excluded.hash,
    fetched_at     = excluded.fetched_at,
    updated_at     = now();
  get diagnostics n = row_count;
  return n;
end;
$$;

revoke all on function public.upsert_events(jsonb) from public, anon, authenticated;
revoke all on function public.resolve_place(text, text, double precision, double precision) from public, anon, authenticated;
grant execute on function public.upsert_events(jsonb) to service_role;

alter table public.events enable row level security;
alter table public.place  enable row level security;

-- Публичное чтение только через представление; таблицы закрыты.
drop policy if exists "read approved" on public.events;
create policy "read approved" on public.events
  for select using (status = 'approved');

grant select on public.events_public to anon, authenticated;
